### ISSUE TITLE
Implement similarity measures

### ISSUE THREAD

**Issue by Jxshyz** [tis22/image_recommender#11]
We should define 3 similarity measures. 

i suggest writting them into seperator scripts.

- Image should be transformed using preprocess pipeline
- similarity measure should be calculated, loading our feature_df from pickle
- return the 5 most similar pictures using .argsort()
- catch the 5 most similar pictures from sqlite
- show the pictures next to the input picture

### Bottleneck will be
the time we need to compute similarities.
Florian mentioned we need to find a suitable library - for now i suggest parallelizing with numba.

**Comment by tis22** [comment]
The database does not have to be used for this yet!

**Comment by tis22** [comment]
In our current code, the similarity measures discussed in the lecture are defined as empty functions with pass.

Please implement these according to the live codings (as discussed earlier).

Make sure they work with two input vectors as e.g. the RGB histogram vectors (a list of floats).
